---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBvJFRxxoDrDyDYgZJV8GAzbUyLChOVUAMqQ7e0YgIaFLWHdWil5oOZbgeF8LsNMBSLLv1YYkcfR2k74E76EHvzwcIgukohWjw5d+E2JNujUldY6tyZX1eSFB/IsAQdMcp1o7KokF6b9aHdvtNFMMbVX65vwDNkDykX5N2ruaLP5dXFDiju9WVoMWH//EQrk835tyPT72O+lT3V/IHewLB0ziv2wOuqkhCYSuNF2xv4SlKWmR//xdSLGK6DIvcyypPmtWxjwIYpn/ZVkalfWOqDvW3mFhigEYp4v3JCcQJ2eoQcnCmtN22/6AQg2c3Zgw3M80Ix3HypQxGjHPUBs9tjec3yozrPqZVvUrf61r0NYujPL6MW7o9gAJl+QNXKuzYkIzJK76hOOSlZMMY66ByULVGVbv3eljnCx/9wqAtPmcOoUC9mmp4mSJtIgMYMe8g7AShTFULBOAn6HEI4gLyq3oxSy/7wrWm2kT2RQc2kYKo4b9hcF+D6KhQSSbCgAhksEQgJbW3SspPb93SC5TnLf4dn+06OvboxvJz3CXOp3J74wZvpSn3hRWX+hLF+pXIQN3AzUqh+IOQ8F7753y1VShXKR2BlGdHuySKTHf4pMSUwDBVfcwKKhlEKZJUDsSVKeATT70O82h6VluuElrmuXfaIugTEjK8h/rWXn/Uj/y9rISGLDQqaeDCPs8nIsJSWtfmDo0521CnLFfR4z1wHOgEewXC89eYTw+haH7mVbl8177nnfbZT
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
